// common
export const REQUEST = "REQUEST";

export const FAILURE = "FAILURE";

// REGISTER

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

// LOGIN

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// LOGOUT

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// GET CURRENT USER

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";